import { useState } from "react";
import { useQuery, useMutation } from "@tanstack/react-query";
import { FileText, Sparkles, Calendar } from "lucide-react";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from "@/components/ui/select";
import { Skeleton } from "@/components/ui/skeleton";
import { useToast } from "@/components/hooks/use-toast";
import api from "@/lib/axios";

const months = Array.from({ length: 12 }, (_, i) => {
  const d = new Date();
  d.setMonth(d.getMonth() - i);
  return d.toISOString().slice(0, 7);
});

export default function AiReportPage() {
  const [selectedMonth, setSelectedMonth] = useState(
    new Date().toISOString().slice(0, 7),
  );
  const { toast } = useToast();

  const { data, isLoading, refetch } = useQuery({
    queryKey: ["ai-report", selectedMonth],
    queryFn: () =>
      api.get(`/ai/reports/${selectedMonth}`).then((r) => r.data.report),
    retry: false,
  });

  const generateMutation = useMutation({
    mutationFn: () => api.post(`/ai/reports/${selectedMonth}/generate`),
    onSuccess: () => {
      toast({ title: "Report generated successfully" });
      refetch();
    },
    onError: (err) => {
      toast({
        title: "Error",
        description: err.response?.data?.error?.message,
        variant: "destructive",
      });
    },
  });

  return (
    <div className="space-y-6">
      <div className="flex items-center justify-between flex-wrap gap-3">
        <div>
          <h1 className="text-2xl font-bold text-gray-200">
            AI Monthly Report
          </h1>
          <p className="text-gray-500 text-sm mt-1">
            AI-generated financial narrative
          </p>
        </div>
        <div className="flex items-center gap-3">
          <Select value={selectedMonth} onValueChange={setSelectedMonth}>
            <SelectTrigger className="w-40">
              <Calendar className="w-4 h-4 mr-2" />
              <SelectValue />
            </SelectTrigger>
            <SelectContent>
              {months.map((m) => (
                <SelectItem key={m} value={m}>
                  {m}
                </SelectItem>
              ))}
            </SelectContent>
          </Select>
          <Button
            className="bg-blue-600 hover:bg-blue-700"
            onClick={() => generateMutation.mutate()}
            disabled={generateMutation.isPending}
          >
            <Sparkles className="w-4 h-4 mr-2" />
            {generateMutation.isPending ? "Generating..." : "Generate Report"}
          </Button>
        </div>
      </div>

      <Card className="border-0 shadow-sm">
        <CardHeader>
          <CardTitle className="text-base flex items-center gap-2">
            <FileText className="w-4 h-4 text-blue-600" />
            Financial Report — {selectedMonth}
          </CardTitle>
        </CardHeader>
        <CardContent>
          {isLoading ? (
            <div className="space-y-3">
              {Array(6)
                .fill(0)
                .map((_, i) => (
                  <Skeleton key={i} className="h-4 rounded" />
                ))}
            </div>
          ) : data ? (
            <div className="space-y-4">
              <div className="prose prose-sm max-w-none text-gray-700 leading-relaxed whitespace-pre-wrap">
                {data.narrative}
              </div>
              <div className="pt-4 border-t border-gray-100 flex items-center justify-between text-xs text-gray-400">
                <span>Generated by {data.modelUsed}</span>
                <span>{new Date(data.generatedAt).toLocaleString()}</span>
              </div>
            </div>
          ) : (
            <div className="text-center py-16 text-gray-400">
              <Sparkles className="w-10 h-10 mx-auto mb-3 opacity-40" />
              <p className="font-medium">No report for {selectedMonth}</p>
              <p className="text-sm mt-1">
                Click Generate Report to create one using AI
              </p>
            </div>
          )}
        </CardContent>
      </Card>
    </div>
  );
}
